# Generated by Django 5.2 on 2025-04-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_remove_phone_image_phone_1_phone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='1',
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.URLField(default='https://t4.ftcdn.net/jpg/07/60/69/29/360_F_760692902_CSWwEZ356IjrXP4nRluyRpsG0Xpr7VRl.jpg'),
        ),
    ]
